.TH "LIST" "8" "December 2015" "" ""
.SH "NAME"
\fBlist\fR - testing \[cq]em lists
.SH "DESCRIPTION"
.RS 0
.IP 1. 4
This is an ordered list
.RS 4
.IP \(bu 4
This is an unordered list
.RS 4
.IP \(bu 4
With a sublist
.RS 4
.IP \(bu 4
And other sublist!
.RE 0

.RE 0

.RE 0

.RE 0


\(em\(em\(em
.RS 0
.IP 9. 4
This is also an ordered list;
.IP 10. 4
And this.
.RE 0
