.TH "ROFF\[ul]ENTITIES" "7" "July 2015" "" ""
.SH "NAME"
\fBroff_entities\fR - list of roffable entities
.RS 0
.IP \(bu 4
\fB\[dq]\fR
.IP \(bu 4
\fB\[sh]\fR
.IP \(bu 4
\fB\[Do]\fR
.IP \(bu 4
\fB\[aq]\fR
.IP \(bu 4
\fB\[pl]\fR
.IP \(bu 4
\fB\[sl]\fR
.IP \(bu 4
\fB\[eq]\fR
.IP \(bu 4
\fB\[!=]\fR
.IP \(bu 4
\fB\[at]\fR
.IP \(bu 4
\fB\[`A]\fR
.IP \(bu 4
\fB\['A]\fR
.IP \(bu 4
\fB\[^A]\fR
.IP \(bu 4
\fB\[~A]\fR
.IP \(bu 4
\fB\[:A]\fR
.IP \(bu 4
\fB\[oA]\fR
.IP \(bu 4
\fB\['C]\fR
.IP \(bu 4
\fB\[,C]\fR
.IP \(bu 4
\fB\[`E]\fR
.IP \(bu 4
\fB\['E]\fR
.IP \(bu 4
\fB\[^E]\fR
.IP \(bu 4
\fB\[:E]\fR
.IP \(bu 4
\fB\[`I]\fR
.IP \(bu 4
\fB\['I]\fR
.IP \(bu 4
\fB\[^I]\fR
.IP \(bu 4
\fB\[:I]\fR
.IP \(bu 4
\fB\[~N]\fR
.IP \(bu 4
\fB\[`O]\fR
.IP \(bu 4
\fB\['O]\fR
.IP \(bu 4
\fB\[^O]\fR
.IP \(bu 4
\fB\[~O]\fR
.IP \(bu 4
\fB\[:O]\fR
.IP \(bu 4
\fB\[vS]\fR
.IP \(bu 4
\fB\[`U]\fR
.IP \(bu 4
\fB\['U]\fR
.IP \(bu 4
\fB\[^U]\fR
.IP \(bu 4
\fB\[:U]\fR
.IP \(bu 4
\fB\['Y]\fR
.IP \(bu 4
\fB\[:Y]\fR
.IP \(bu 4
\fB\[vZ]\fR
.IP \(bu 4
\fB\[lB]\fR
.IP \(bu 4
\fB\[rs]\fR
.IP \(bu 4
\fB\[rB]\fR
.IP \(bu 4
\fB\[ha]\fR
.IP \(bu 4
\fB\[ul]\fR
.IP \(bu 4
\fB\fR \[ga]
.IP \(bu 4
\fB\[`a]\fR
.IP \(bu 4
\fB\['a]\fR
.IP \(bu 4
\fB\[^a]\fR
.IP \(bu 4
\fB\[~a]\fR
.IP \(bu 4
\fB\[:a]\fR
.IP \(bu 4
\fB\[oa]\fR
.IP \(bu 4
\fB\['c]\fR
.IP \(bu 4
\fB\[,c]\fR
.IP \(bu 4
\fB\[`e]\fR
.IP \(bu 4
\fB\['e]\fR
.IP \(bu 4
\fB\[^e]\fR
.IP \(bu 4
\fB\[:e]\fR
.IP \(bu 4
\fB\[Fi]\fR
.IP \(bu 4
\fB\[Fl]\fR
.IP \(bu 4
\fB\[`i]\fR
.IP \(bu 4
\fB\['i]\fR
.IP \(bu 4
\fB\[^i]\fR
.IP \(bu 4
\fB\[:i]\fR
.IP \(bu 4
\fB\[~n]\fR
.IP \(bu 4
\fB\[`o]\fR
.IP \(bu 4
\fB\['o]\fR
.IP \(bu 4
\fB\[^o]\fR
.IP \(bu 4
\fB\[~o]\fR
.IP \(bu 4
\fB\[:o]\fR
.IP \(bu 4
\fB\[vs]\fR
.IP \(bu 4
\fB\[`u]\fR
.IP \(bu 4
\fB\['u]\fR
.IP \(bu 4
\fB\[^u]\fR
.IP \(bu 4
\fB\[:u]\fR
.IP \(bu 4
\fB\['y]\fR
.IP \(bu 4
\fB\[:y]\fR
.IP \(bu 4
\fB\[vz]\fR
.IP \(bu 4
\fB\[lC]\fR
.IP \(bu 4
\fB\[ba]\fR
.IP \(bu 4
\fB\[rC]\fR
.IP \(bu 4
\fB\[ti]\fR
.IP \(bu 4
\fB\[r!]\fR
.IP \(bu 4
\fB\[ct]\fR
.IP \(bu 4
\fB\[Po]\fR
.IP \(bu 4
\fB\[Cs]\fR
.IP \(bu 4
\fB\[Ye]\fR
.IP \(bu 4
\fB\[bb]\fR
.IP \(bu 4
\fB\[sc]\fR
.IP \(bu 4
\fB\[ad]\fR
.IP \(bu 4
\fB\[co]\fR
.IP \(bu 4
\fB\[Of]\fR
.IP \(bu 4
\fB\[Fo]\fR
.IP \(bu 4
\fB\[no]\fR
.IP \(bu 4
\fB\[rg]\fR
.IP \(bu 4
\fB\[a-]\fR
.IP \(bu 4
\fB\[de]\fR
.IP \(bu 4
\fB\[+-]\fR
.IP \(bu 4
\fB\[S2]\fR
.IP \(bu 4
\fB\[S3]\fR
.IP \(bu 4
\fB\[aa]\fR
.IP \(bu 4
\fB\[mc]\fR
.IP \(bu 4
\fB\[ps]\fR
.IP \(bu 4
\fB\[pc]\fR
.IP \(bu 4
\fB\[ac]\fR
.IP \(bu 4
\fB\[S1]\fR
.IP \(bu 4
\fB\[Om]\fR
.IP \(bu 4
\fB\[Fc]\fR
.IP \(bu 4
\fB\[14]\fR
.IP \(bu 4
\fB\[12]\fR
.IP \(bu 4
\fB\[34]\fR
.IP \(bu 4
\fB\[r?]\fR
.IP \(bu 4
\fB\[AE]\fR
.IP \(bu 4
\fB\[-D]\fR
.IP \(bu 4
\fB\[mu]\fR
.IP \(bu 4
\fB\[/O]\fR
.IP \(bu 4
\fB\[TP]\fR
.IP \(bu 4
\fB\[ss]\fR
.IP \(bu 4
\fB\[ae]\fR
.IP \(bu 4
\fB\[Sd]\fR
.IP \(bu 4
\fB\[di]\fR
.IP \(bu 4
\fB\[/o]\fR
.IP \(bu 4
\fB\[Tp]\fR
.IP \(bu 4
\fB\[.i]\fR
.IP \(bu 4
\fB\[IJ]\fR
.IP \(bu 4
\fB\[ij]\fR
.IP \(bu 4
\fB\[/L]\fR
.IP \(bu 4
\fB\[/l]\fR
.IP \(bu 4
\fB\[OE]\fR
.IP \(bu 4
\fB\[oe]\fR
.IP \(bu 4
\fB\[Fn]\fR
.IP \(bu 4
\fB\[.j]\fR
.IP \(bu 4
\fB\[ah]\fR
.IP \(bu 4
\fB\[ab]\fR
.IP \(bu 4
\fB\[a.]\fR
.IP \(bu 4
\fB\[ao]\fR
.IP \(bu 4
\fB\[ho]\fR
.IP \(bu 4
\fB\[*A]\fR
.IP \(bu 4
\fB\[*B]\fR
.IP \(bu 4
\fB\[*G]\fR
.IP \(bu 4
\fB\[*D]\fR
.IP \(bu 4
\fB\[*E]\fR
.IP \(bu 4
\fB\[*Z]\fR
.IP \(bu 4
\fB\[*Y]\fR
.IP \(bu 4
\fB\[*H]\fR
.IP \(bu 4
\fB\[*I]\fR
.IP \(bu 4
\fB\[*K]\fR
.IP \(bu 4
\fB\[*L]\fR
.IP \(bu 4
\fB\[*M]\fR
.IP \(bu 4
\fB\[*N]\fR
.IP \(bu 4
\fB\[*C]\fR
.IP \(bu 4
\fB\[*O]\fR
.IP \(bu 4
\fB\[*P]\fR
.IP \(bu 4
\fB\[*R]\fR
.IP \(bu 4
\fB\[*S]\fR
.IP \(bu 4
\fB\[*T]\fR
.IP \(bu 4
\fB\[*U]\fR
.IP \(bu 4
\fB\[*F]\fR
.IP \(bu 4
\fB\[*X]\fR
.IP \(bu 4
\fB\[*Q]\fR
.IP \(bu 4
\fB\[*W]\fR
.IP \(bu 4
\fB\[*a]\fR
.IP \(bu 4
\fB\[*b]\fR
.IP \(bu 4
\fB\[*g]\fR
.IP \(bu 4
\fB\[*d]\fR
.IP \(bu 4
\fB\[*e]\fR
.IP \(bu 4
\fB\[*z]\fR
.IP \(bu 4
\fB\[*y]\fR
.IP \(bu 4
\fB\[*h]\fR
.IP \(bu 4
\fB\[*i]\fR
.IP \(bu 4
\fB\[*k]\fR
.IP \(bu 4
\fB\[*l]\fR
.IP \(bu 4
\fB\[*m]\fR
.IP \(bu 4
\fB\[*n]\fR
.IP \(bu 4
\fB\[*c]\fR
.IP \(bu 4
\fB\[*o]\fR
.IP \(bu 4
\fB\[*p]\fR
.IP \(bu 4
\fB\[*r]\fR
.IP \(bu 4
\fB\[ts]\fR
.IP \(bu 4
\fB\[*s]\fR
.IP \(bu 4
\fB\[*t]\fR
.IP \(bu 4
\fB\[*u]\fR
.IP \(bu 4
\fB\[+f]\fR
.IP \(bu 4
\fB\[*x]\fR
.IP \(bu 4
\fB\[*q]\fR
.IP \(bu 4
\fB\[*w]\fR
.IP \(bu 4
\fB\[+h]\fR
.IP \(bu 4
\fB\[*f]\fR
.IP \(bu 4
\fB\[+p]\fR
.IP \(bu 4
\fB\[+e]\fR
.IP \(bu 4
\fB\[hy]\fR
.IP \(bu 4
\fB\[en]\fR
.IP \(bu 4
\fB\[em]\fR
.IP \(bu 4
\fB\[oq]\fR
.IP \(bu 4
\fB\[cq]\fR
.IP \(bu 4
\fB\[bq]\fR
.IP \(bu 4
\fB\[lq]\fR
.IP \(bu 4
\fB\[rq]\fR
.IP \(bu 4
\fB\[Bq]\fR
.IP \(bu 4
\fB\[dg]\fR
.IP \(bu 4
\fB\[dd]\fR
.IP \(bu 4
\fB\[bu]\fR
.IP \(bu 4
\fB\[%0]\fR
.IP \(bu 4
\fB\[fm]\fR
.IP \(bu 4
\fB\[sd]\fR
.IP \(bu 4
\fB\[fo]\fR
.IP \(bu 4
\fB\[fc]\fR
.IP \(bu 4
\fB\[rn]\fR
.IP \(bu 4
\fB\[f/]\fR
.IP \(bu 4
\fB\[Eu]\fR
.IP \(bu 4
\fB\[-h]\fR
.IP \(bu 4
\fB\[Im]\fR
.IP \(bu 4
\fB\[wp]\fR
.IP \(bu 4
\fB\[Re]\fR
.IP \(bu 4
\fB\[tm]\fR
.IP \(bu 4
\fB\[Ah]\fR
.IP \(bu 4
\fB\[18]\fR
.IP \(bu 4
\fB\[38]\fR
.IP \(bu 4
\fB\[58]\fR
.IP \(bu 4
\fB\[78]\fR
.IP \(bu 4
\fB\[<-]\fR
.IP \(bu 4
\fB\[ua]\fR
.IP \(bu 4
\fB\[->]\fR
.IP \(bu 4
\fB\[da]\fR
.IP \(bu 4
\fB\[<>]\fR
.IP \(bu 4
\fB\[va]\fR
.IP \(bu 4
\fB\[CR]\fR
.IP \(bu 4
\fB\[lA]\fR
.IP \(bu 4
\fB\[uA]\fR
.IP \(bu 4
\fB\[rA]\fR
.IP \(bu 4
\fB\[dA]\fR
.IP \(bu 4
\fB\[hA]\fR
.IP \(bu 4
\fB\[vA]\fR
.IP \(bu 4
\fB\[fa]\fR
.IP \(bu 4
\fB\[pd]\fR
.IP \(bu 4
\fB\[te]\fR
.IP \(bu 4
\fB\[es]\fR
.IP \(bu 4
\fB\[gr]\fR
.IP \(bu 4
\fB\[mo]\fR
.IP \(bu 4
\fB\[nm]\fR
.IP \(bu 4
\fB\[st]\fR
.IP \(bu 4
\fB\[product]\fR
.IP \(bu 4
\fB\[coproduct]\fR
.IP \(bu 4
\fB\[sum]\fR
.IP \(bu 4
\fB\[mi]\fR
.IP \(bu 4
\fB\[-+]\fR
.IP \(bu 4
\fB\[**]\fR
.IP \(bu 4
\fB\[sr]\fR
.IP \(bu 4
\fB\[pt]\fR
.IP \(bu 4
\fB\[if]\fR
.IP \(bu 4
\fB\[/_]\fR
.IP \(bu 4
\fB\[AN]\fR
.IP \(bu 4
\fB\[OR]\fR
.IP \(bu 4
\fB\[ca]\fR
.IP \(bu 4
\fB\[cu]\fR
.IP \(bu 4
\fB\[is]\fR
.IP \(bu 4
\fB\[tf]\fR
.IP \(bu 4
\fB\[ap]\fR
.IP \(bu 4
\fB\[|=]\fR
.IP \(bu 4
\fB\[=~]\fR
.IP \(bu 4
\fB\[~~]\fR
.IP \(bu 4
\fB\[==]\fR
.IP \(bu 4
\fB\[ne]\fR
.IP \(bu 4
\fB\[<=]\fR
.IP \(bu 4
\fB\[>=]\fR
.IP \(bu 4
\fB\[>>]\fR
.IP \(bu 4
\fB\[<<]\fR
.IP \(bu 4
\fB\[sb]\fR
.IP \(bu 4
\fB\[nb]\fR
.IP \(bu 4
\fB\[sp]\fR
.IP \(bu 4
\fB\[nc]\fR
.IP \(bu 4
\fB\[ib]\fR
.IP \(bu 4
\fB\[ip]\fR
.IP \(bu 4
\fB\[c+]\fR
.IP \(bu 4
\fB\[c*]\fR
.IP \(bu 4
\fB\[pp]\fR
.IP \(bu 4
\fB\[md]\fR
.IP \(bu 4
\fB\[lc]\fR
.IP \(bu 4
\fB\[rc]\fR
.IP \(bu 4
\fB\[lf]\fR
.IP \(bu 4
\fB\[rf]\fR
.IP \(bu 4
\fB\[parenlefttp]\fR
.IP \(bu 4
\fB\[parenleftex]\fR
.IP \(bu 4
\fB\[parenleftbt]\fR
.IP \(bu 4
\fB\[parenrighttp]\fR
.IP \(bu 4
\fB\[parenrightex]\fR
.IP \(bu 4
\fB\[parenrightbt]\fR
.IP \(bu 4
\fB\[bracketleftex]\fR
.IP \(bu 4
\fB\[bracketrightex]\fR
.IP \(bu 4
\fB\[lt]\fR
.IP \(bu 4
\fB\[lk]\fR
.IP \(bu 4
\fB\[lb]\fR
.IP \(bu 4
\fB\[bv]\fR
.IP \(bu 4
\fB\[rt]\fR
.IP \(bu 4
\fB\[rk]\fR
.IP \(bu 4
\fB\[rb]\fR
.IP \(bu 4
\fB\[an]\fR
.IP \(bu 4
\fB\[br]\fR
.IP \(bu 4
\fB\[sq]\fR
.IP \(bu 4
\fB\[lz]\fR
.IP \(bu 4
\fB\[ci]\fR
.IP \(bu 4
\fB\[lh]\fR
.IP \(bu 4
\fB\[rh]\fR
.IP \(bu 4
\fB\[SP]\fR
.IP \(bu 4
\fB\[CL]\fR
.IP \(bu 4
\fB\[HE]\fR
.IP \(bu 4
\fB\[DI]\fR
.IP \(bu 4
\fB\[OK]\fR
.IP \(bu 4
\fB\[la]\fR
.IP \(bu 4
\fB\[ra]\fR
.RE 0
