.TH "BLOCKQUOTE" "8" "July 2015" "" ""
.SH "NAME"
\fBblockquote\fR - Blockquote.
.SH "DESCRIPTION"
.P
This is a paragraph.
.RS 0
.P
This is a very standard block quote.
.P
But, it has a list:
.RS 4
.IP \(bu 4
Alpha;
.IP \(bu 4
Bravo;
.IP \(bu 4
Charlie.
.RE 0

.RS 4
.P
With another block quote.
.RS 4
.P
And other.
.RE 0

.RE 0

.RE 0

.P
This is also paragraph.
