.TH "LINK" "8" "June 2015" "" ""
.SH "NAME"
\fBlink\fR - testing \[cq]em H-refs
.SH "DESCRIPTION"
.P
This is an auto-link: \fIhttp://example.com\fR.
.P
This is a normal link \fIhttp://example.com\fR.
.P
This is a normal link with title \fIhttp://example.com\fR.
.P
This is an empty link (WEIRD!) \fIhttp://example.com\fR.
.P
This is a normal image \fIhttp://example.com/favicon.ico\fR.
.P
This is a normal image with title \fIhttp://example.com/favicon.ico\fR.
.P
This is an empty image null\fIhttp://example.com/favicon.ico\fR.
.P
This is a link reference \fIhttp://example.com\fR.
.P
This is an image reference \fIhttp://example.com/favicon.ico\fR.
.P
This is an invalid reference.
