.TH "LINK" "8" "August 2015" "" ""
.SH "NAME"
\fBlink\fR - testing \[cq]em H-refs
.SH "DESCRIPTION"
.P
This is an auto-link: \fI\(lahttp:\[sl]\[sl]example.com\(ra\fR.
.P
This is a \fBnormal link\fR \fI\(lahttp:\[sl]\[sl]example.com\(ra\fR.
.P
This is a \fBnormal link with title\fR \fI\(lahttp:\[sl]\[sl]example.com\(ra\fR.
.P
This is an empty link (WEIRD!) \fI\(lahttp:\[sl]\[sl]example.com\(ra\fR.
.P
This is a \fBnormal image\fR \fI\(lahttp:\[sl]\[sl]example.com\[sl]favicon.ico\(ra\fR.
.P
This is a \fBnormal image with title\fR \fI\(lahttp:\[sl]\[sl]example.com\[sl]favicon.ico\(ra\fR.
.P
This is an empty image null\fI\(lahttp:\[sl]\[sl]example.com\[sl]favicon.ico\(ra\fR.
.P
This is a \fBlink reference\fR \fI\(lahttp:\[sl]\[sl]example.com\(ra\fR.
.P
This is an \fBimage reference\fR \fI\(lahttp:\[sl]\[sl]example.com\[sl]favicon.ico\(ra\fR.
.P
This is an \fBinvalid reference\fR.
