.TH "LINK" "8" "February 2016" "" ""
.SH "NAME"
\fBlink\fR - testing \[cq]em H-refs
.SH "DESCRIPTION"
.P
This is an auto-link: \fI\(lahttp://example.com\(ra\fR.
.P
This is a \fBnormal link\fR \fI\(lahttp://example.com\(ra\fR.
.P
This is a \fBnormal link with title\fR \fI\(lahttp://example.com\(ra\fR.
.P
This is an empty link (WEIRD!) \fI\(lahttp://example.com\(ra\fR.
.P
This is a \fBnormal image\fR \fI\(lahttp://example.com/favicon.ico\(ra\fR.
.P
This is a \fBnormal image with title\fR \fI\(lahttp://example.com/favicon.ico\(ra\fR.
.P
This is an empty image null\fI\(lahttp://example.com/favicon.ico\(ra\fR.
.P
This is a \fBlink reference\fR \fI\(lahttp://example.com\(ra\fR.
.P
This is an \fBimage reference\fR \fI\(lahttp://example.com/favicon.ico\(ra\fR.
.P
This is an \fBinvalid reference\fR.
